### ISSUE TITLE
Encounter bug (flex related) in the make process

### ISSUE THREAD

**Issue by softpudding** [InitialDLab/XDB#6]
Hi, I'm trying to install XDB in my system. During the make process, I encounter this problem:

_gram.c:64:25: error: conflicting types for ‘base_yylex’
 #define yylex           base_yylex
                         ^
scan.c:9113:12: note: in expansion of macro ‘yylex’
 extern int yylex \
            ^~~~~
In file included from gram.y:59:0:
../../../src/include/parser/gramparse.h:66:12: note: previous declaration of ‘base_yylex’ was here
 extern int base_yylex(YYSTYPE *lvalp, YYLTYPE *llocp,
            ^~~~~~~~~~
gram.c:64:25: error: conflicting types for ‘base_yylex’
 #define yylex           base_yylex
                         ^
scan.c:9116:21: note: in expansion of macro ‘yylex’
 #define YY_DECL int yylex \
                     ^~~~~
scan.c:9137:1: note: in expansion of macro ‘YY_DECL’
 YY_DECL
 ^~~~~~~
In file included from gram.y:59:0:
../../../src/include/parser/gramparse.h:66:12: note: previous declaration of ‘base_yylex’ was here
 extern int base_yylex(YYSTYPE *lvalp, YYLTYPE *llocp,
            ^~~~~~~~~~
<builtin>: recipe for target 'gram.o' failed_

I think this is something related to parser, maybe my flex version isn't correct. I tried flex version 2.5.31, 2.5.39, 2.6.0 and later, but none of them works. Can you kindly tell me the flex or bison version you used to build the XDB?

**Comment by zzy7896321** [comment]
Hi there.

I think any flex >= 2.5.31 but smaller than 2.6.x should work. That was a bug in the autoconf script for determining flex version in the old PostgreSQL release. We recently built it successfully using flex 2.5.35 and bison 3.5.1.

You might want to delete gram.c, gram.h and scan.c in src/backend/parser manually if you install and reconfigure the build system, because they are not automatically updated.

Let me know if that doesn't work for you.

**Comment by softpudding** [comment]
It solved! Thanks.
